### ISSUE TITLE
fes2022.yml configuration

### ISSUE THREAD

**Issue by leandrof-ing** [kvos/CoastSat#555]
![img-a kvos](https://github.com/user-attachments/assets/53036e20-b71f-4df4-bc28-e4f1c27d9aee)

Hi Killian. Im trying to install coastsat, and i don´t know what i need to write in fes2022.yml data, In the fes2022.yml file, to replace the routes for the tide, do we have to write ocean_tide_extrapolated? Or does ocean_tide go there?
Best regards,

**Comment by kvos** [comment]
hi @leandrof-ing , you need to put ocean_tide. 
See my folder structure as example:
![image](https://github.com/user-attachments/assets/801384d5-8474-4254-9b7e-241bb0971609)

With each subfolder (/ocean_tide and /load_tide) containing 34 constituents:
![image](https://github.com/user-attachments/assets/b61b3784-7377-4a4a-ba63-1dc05d5ac8a9)

And fes2022.yaml with the absolute paths to each file:
```
radial:
  cartesian:
    amplitude: amplitude
    latitude: lat
    longitude: lon
    paths:
      2N2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\2n2_fes2022.nc
      Eps2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\eps2_fes2022.nc
      J1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\j1_fes2022.nc
      K1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\k1_fes2022.nc
      K2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\k2_fes2022.nc
      L2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\l2_fes2022.nc
      Lambda2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\lambda2_fes2022.nc
      M2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\m2_fes2022.nc
      M3: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\m3_fes2022.nc
      M4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\m4_fes2022.nc
      M6: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\m6_fes2022.nc
      M8: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\m8_fes2022.nc
      MKS2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\mks2_fes2022.nc
      MN4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\mn4_fes2022.nc
      MS4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\ms4_fes2022.nc
      MSf: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\msf_fes2022.nc
      Mf: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\mf_fes2022.nc
      Mm: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\mm_fes2022.nc
      Msqm: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\msqm_fes2022.nc
      Mtm: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\mtm_fes2022.nc
      Mu2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\mu2_fes2022.nc
      N2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\n2_fes2022.nc
      N4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\n4_fes2022.nc
      Nu2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\nu2_fes2022.nc
      O1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\o1_fes2022.nc
      P1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\p1_fes2022.nc
      Q1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\q1_fes2022.nc
      R2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\r2_fes2022.nc
      S1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\s1_fes2022.nc
      S2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\s2_fes2022.nc
      S4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\s4_fes2022.nc
      Sa: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\sa_fes2022.nc
      Ssa: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\ssa_fes2022.nc
      T2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\load_tide\t2_fes2022.nc
    phase: phase
tide:
  cartesian:
    amplitude: amplitude
    dynamic:
    - A5
    latitude: lat
    longitude: lon
    paths:
      2N2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\2n2_fes2022.nc
      Eps2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\eps2_fes2022.nc
      J1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\j1_fes2022.nc
      K1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\k1_fes2022.nc
      K2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\k2_fes2022.nc
      L2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\l2_fes2022.nc
      Lambda2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\lambda2_fes2022.nc
      M2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\m2_fes2022.nc
      M3: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\m3_fes2022.nc
      M4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\m4_fes2022.nc
      M6: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\m6_fes2022.nc
      M8: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\m8_fes2022.nc
      MKS2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\mks2_fes2022.nc
      MN4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\mn4_fes2022.nc
      MS4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\ms4_fes2022.nc
      MSf: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\msf_fes2022.nc
      Mf: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\mf_fes2022.nc
      Mm: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\mm_fes2022.nc
      Msqm: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\msqm_fes2022.nc
      Mtm: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\mtm_fes2022.nc
      Mu2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\mu2_fes2022.nc
      N2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\n2_fes2022.nc
      N4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\n4_fes2022.nc
      Nu2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\nu2_fes2022.nc
      O1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\o1_fes2022.nc
      P1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\p1_fes2022.nc
      Q1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\q1_fes2022.nc
      R2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\r2_fes2022.nc
      S1: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\s1_fes2022.nc
      S2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\s2_fes2022.nc
      S4: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\s4_fes2022.nc
      Sa: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\sa_fes2022.nc
      Ssa: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\ssa_fes2022.nc
      T2: C:\Users\kilia\Documents\GitHub\CoastSat.webgis\aviso-fes-main\data\fes2022b\ocean_tide\t2_fes2022.nc
    phase: phase
```
